name: Build and Push Docker Images

on:
  push:
    # branches:
    #   - main  # Change this to your default branch
    tags:
      - v*  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push bun app
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: |
            sa2avroo/lms-server-node:latest
            sa2avroo/lms-server-node:${{ github.sha }}
            sa2avroo/lms-server-node:${{ github.ref_name }}

      - name: Logout from Docker Hub
        run: docker logout